export default [
  {
    gjhdqsz_dm: '234',
    gjhdqmc: '法罗群岛',
    gjhdqjc: '法罗群岛',
    gjhdqywmc: 'Faroe Islands',
    gjhdqywjc: 'FAROEISLANDS',
    gjhdqszm_dm: 'FRO',
    gjhdqlzm_dm: 'FO',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '266',
    gjhdqmc: '加蓬共和国',
    gjhdqjc: '加蓬',
    gjhdqywmc: 'Gabonese Republic',
    gjhdqywjc: 'GABON',
    gjhdqszm_dm: 'GAB',
    gjhdqlzm_dm: 'GA',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '300',
    gjhdqmc: '希腊共和国',
    gjhdqjc: '希腊',
    gjhdqywmc: 'Hellenic Republic',
    gjhdqywjc: 'GREECE',
    gjhdqszm_dm: 'GRC',
    gjhdqlzm_dm: 'GR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '492',
    gjhdqmc: '摩纳哥公国',
    gjhdqjc: '摩纳哥',
    gjhdqywmc: 'Principality of Monaco',
    gjhdqywjc: 'MONACO',
    gjhdqszm_dm: 'MCO',
    gjhdqlzm_dm: 'MC',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '600',
    gjhdqmc: '巴拉圭共和国',
    gjhdqjc: '巴拉圭',
    gjhdqywmc: 'Republic of Paraguay',
    gjhdqywjc: 'PARAGUAY',
    gjhdqszm_dm: 'PRY',
    gjhdqlzm_dm: 'PY',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '894',
    gjhdqmc: '赞比亚共和国',
    gjhdqjc: '赞比亚',
    gjhdqywmc: 'Republic of Zambia',
    gjhdqywjc: 'ZAMBIA',
    gjhdqszm_dm: 'ZMB',
    gjhdqlzm_dm: 'ZM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '048',
    gjhdqmc: '巴林国',
    gjhdqjc: '巴林',
    gjhdqywmc: 'State of Bahrain',
    gjhdqywjc: 'BAHRAIN',
    gjhdqszm_dm: 'BHR',
    gjhdqlzm_dm: 'BH',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '332',
    gjhdqmc: '海地共和国',
    gjhdqjc: '海地',
    gjhdqywmc: 'Republic of Haiti',
    gjhdqywjc: 'HAITI',
    gjhdqszm_dm: 'HTI',
    gjhdqlzm_dm: 'HT',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '398',
    gjhdqmc: '哈萨克斯坦共和国',
    gjhdqjc: '哈萨克斯坦',
    gjhdqywmc: 'Republic of Kazakhstan',
    gjhdqywjc: 'KAZAKHSTAN',
    gjhdqszm_dm: 'KAZ',
    gjhdqlzm_dm: 'KZ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '678',
    gjhdqmc: '圣多美和普林西比民主共和国',
    gjhdqjc: '圣多美和普林西比',
    gjhdqywmc: 'Democratic Republic of Sao Tomeand Principe',
    gjhdqywjc: 'SAOTOMEANDPRINCIPE',
    gjhdqszm_dm: 'STP',
    gjhdqlzm_dm: 'ST',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '796',
    gjhdqmc: '特克斯和凯科斯群岛',
    gjhdqjc: '特克斯和凯科斯群岛',
    gjhdqywmc: 'Turksand Caicos Islands',
    gjhdqywjc: 'TURKSANDCAICOSISLANDS',
    gjhdqszm_dm: 'TCA',
    gjhdqlzm_dm: 'TC',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '336',
    gjhdqmc: '梵蒂冈城国',
    gjhdqjc: '梵蒂冈',
    gjhdqywmc: 'Vatican City State',
    gjhdqywjc: 'VATICAN',
    gjhdqszm_dm: 'VAT',
    gjhdqlzm_dm: 'VA',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '008',
    gjhdqmc: '阿尔巴尼亚共和国',
    gjhdqjc: '阿尔巴尼亚',
    gjhdqywmc: 'Republic of Albania',
    gjhdqywjc: 'ALBANIA',
    gjhdqszm_dm: 'ALB',
    gjhdqlzm_dm: 'AL',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '533',
    gjhdqmc: '阿鲁巴',
    gjhdqjc: '阿鲁巴',
    gjhdqywmc: 'Aruba',
    gjhdqywjc: 'ARUBA',
    gjhdqszm_dm: 'ABW',
    gjhdqlzm_dm: 'AW',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '052',
    gjhdqmc: '巴巴多斯',
    gjhdqjc: '巴巴多斯',
    gjhdqywmc: 'Barbados',
    gjhdqywjc: 'BARBADOS',
    gjhdqszm_dm: 'BRB',
    gjhdqlzm_dm: 'BB',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '070',
    gjhdqmc: '波斯尼亚和黑塞哥维那',
    gjhdqjc: '波黑',
    gjhdqywmc: 'Bosnia and Herzegovina',
    gjhdqywjc: 'BOSNIAANDHERZEGOVINA',
    gjhdqszm_dm: 'BIH',
    gjhdqlzm_dm: 'BA',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '218',
    gjhdqmc: '厄瓜多尔共和国',
    gjhdqjc: '厄瓜多尔',
    gjhdqywmc: 'Republic of Ecuador',
    gjhdqywjc: 'ECUADOR',
    gjhdqszm_dm: 'ECU',
    gjhdqlzm_dm: 'EC',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '516',
    gjhdqmc: '纳米比亚共和国',
    gjhdqjc: '纳米比亚',
    gjhdqywmc: 'Republic of Namibia',
    gjhdqywjc: 'NAMIBIA',
    gjhdqszm_dm: 'NAM',
    gjhdqlzm_dm: 'NA',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '646',
    gjhdqmc: '卢旺达共和国',
    gjhdqjc: '卢旺达',
    gjhdqywmc: 'Republic of Rwanda',
    gjhdqywjc: 'RWANDA',
    gjhdqszm_dm: 'RWA',
    gjhdqlzm_dm: 'RW',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '674',
    gjhdqmc: '圣马力诺共和国',
    gjhdqjc: '圣马力诺',
    gjhdqywmc: 'Republic of SanMarino',
    gjhdqywjc: 'SANMARINO',
    gjhdqszm_dm: 'SMR',
    gjhdqlzm_dm: 'SM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '682',
    gjhdqmc: '沙特阿拉伯王国',
    gjhdqjc: '沙特阿拉伯',
    gjhdqywmc: 'Kingdom of Saudi Arabia',
    gjhdqywjc: 'SAUDIARABIA',
    gjhdqszm_dm: 'SAU',
    gjhdqlzm_dm: 'SA',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '772',
    gjhdqmc: '托克劳',
    gjhdqjc: '托克劳',
    gjhdqywmc: 'Tokelau',
    gjhdqywjc: 'TOKELAU',
    gjhdqszm_dm: 'TKL',
    gjhdqlzm_dm: 'TK',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '795',
    gjhdqmc: '土库曼斯坦',
    gjhdqjc: '土库曼斯坦',
    gjhdqywmc: 'Turkmenistan',
    gjhdqywjc: 'TURKMENISTAN',
    gjhdqszm_dm: 'TKM',
    gjhdqlzm_dm: 'TM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '124',
    gjhdqmc: '加拿大',
    gjhdqjc: '加拿大',
    gjhdqywmc: 'Canada',
    gjhdqywjc: 'CANADA',
    gjhdqszm_dm: 'CAN',
    gjhdqlzm_dm: 'CA',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '312',
    gjhdqmc: '瓜德罗普',
    gjhdqjc: '瓜德罗普',
    gjhdqywmc: 'Guadeloupe',
    gjhdqywjc: 'GUADELOUPE',
    gjhdqszm_dm: 'GLP',
    gjhdqlzm_dm: 'GP',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '348',
    gjhdqmc: '匈牙利共和国',
    gjhdqjc: '匈牙利',
    gjhdqywmc: 'Republic of Hungary',
    gjhdqywjc: 'HUNGARY',
    gjhdqszm_dm: 'HUN',
    gjhdqlzm_dm: 'HU',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '500',
    gjhdqmc: '蒙特塞拉特',
    gjhdqjc: '蒙特塞拉特',
    gjhdqywmc: 'Montserrat',
    gjhdqywjc: 'MONTSERRAT',
    gjhdqszm_dm: 'MSR',
    gjhdqlzm_dm: 'MS',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '670',
    gjhdqmc: '圣文森特和格林纳丁斯',
    gjhdqjc: '圣文森特和格林纳丁斯',
    gjhdqywmc: 'Saint Vincentand the Grenadines',
    gjhdqywjc: 'SAINTVINCENTANDTHEGRENADINES',
    gjhdqszm_dm: 'VCT',
    gjhdqlzm_dm: 'VC',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '084',
    gjhdqmc: '伯利兹',
    gjhdqjc: '伯利兹',
    gjhdqywmc: 'Belize',
    gjhdqywjc: 'BELIZE',
    gjhdqszm_dm: 'BLZ',
    gjhdqlzm_dm: 'BZ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '344',
    gjhdqmc: '中国香港特别行政区',
    gjhdqjc: '中国香港',
    gjhdqywmc: 'Hong Kong Special Administrative Region of China',
    gjhdqywjc: 'HONG KONG',
    gjhdqszm_dm: 'HKG',
    gjhdqlzm_dm: 'HK',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '626',
    gjhdqmc: '东帝汶',
    gjhdqjc: '东帝汶',
    gjhdqywmc: 'East Timor',
    gjhdqywjc: 'EASTTIMOR',
    gjhdqszm_dm: 'TMP',
    gjhdqlzm_dm: 'TP',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '270',
    gjhdqmc: '冈比亚共和国',
    gjhdqjc: '冈比亚',
    gjhdqywmc: 'Republic of the Gambia',
    gjhdqywjc: 'GAMBIA',
    gjhdqszm_dm: 'GMB',
    gjhdqlzm_dm: 'GM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '580',
    gjhdqmc: '北马里亚纳自由联邦',
    gjhdqjc: '北马里亚纳',
    gjhdqywmc: 'Commonwealth of the Northern Mariana Islands',
    gjhdqywjc: 'NORTHERNMARIANAISLANDS',
    gjhdqszm_dm: 'MNP',
    gjhdqlzm_dm: 'MP',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '736',
    gjhdqmc: '苏丹共和国',
    gjhdqjc: '苏丹',
    gjhdqywmc: 'Republic of the Sudan',
    gjhdqywjc: 'SUDAN',
    gjhdqszm_dm: 'SDN',
    gjhdqlzm_dm: 'SD',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '780',
    gjhdqmc: '特立尼达和多巴哥共和国',
    gjhdqjc: '特立尼达和多巴哥',
    gjhdqywmc: 'Republic of Trinidadand Tobago',
    gjhdqywjc: 'TRINIDADANDTOBAGO',
    gjhdqszm_dm: 'TTO',
    gjhdqlzm_dm: 'TT',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '840',
    gjhdqmc: '美利坚合众国',
    gjhdqjc: '美国',
    gjhdqywmc: 'Unitedstates of America',
    gjhdqywjc: 'UNITEDSTATES',
    gjhdqszm_dm: 'USA',
    gjhdqlzm_dm: 'US',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '012',
    gjhdqmc: '阿尔及利亚民主人民共和国',
    gjhdqjc: '阿尔及利亚',
    gjhdqywmc: "Democratic People's Republic of Algeria",
    gjhdqywjc: 'ALGERIA',
    gjhdqszm_dm: 'DZA',
    gjhdqlzm_dm: 'DZ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '044',
    gjhdqmc: '巴哈马联邦',
    gjhdqjc: '巴哈马',
    gjhdqywmc: 'Commonwealth of the Bahamas',
    gjhdqywjc: 'BAHAMAS',
    gjhdqszm_dm: 'BHS',
    gjhdqlzm_dm: 'BS',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '188',
    gjhdqmc: '哥斯达黎加共和国',
    gjhdqjc: '哥斯达黎加',
    gjhdqywmc: 'Republic of Costa Rica',
    gjhdqywjc: 'COSTARICA',
    gjhdqszm_dm: 'CRI',
    gjhdqlzm_dm: 'CR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '504',
    gjhdqmc: '摩洛哥王国',
    gjhdqjc: '摩洛哥',
    gjhdqywmc: 'Kingdom of Morocco',
    gjhdqywjc: 'MOROCCO',
    gjhdqszm_dm: 'MAR',
    gjhdqlzm_dm: 'MA',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '578',
    gjhdqmc: '挪威王国',
    gjhdqjc: '挪威',
    gjhdqywmc: 'Kingdom of Norway',
    gjhdqywjc: 'NORWAY',
    gjhdqszm_dm: 'NOR',
    gjhdqlzm_dm: 'NO',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '585',
    gjhdqmc: '帕劳共和国',
    gjhdqjc: '帕劳',
    gjhdqywmc: 'Republic of Palau',
    gjhdqywjc: 'PALAU',
    gjhdqszm_dm: 'PLW',
    gjhdqlzm_dm: 'PW',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '598',
    gjhdqmc: '巴布亚新几内亚独立国',
    gjhdqjc: '巴布亚新几内亚',
    gjhdqywmc: 'Independent State of Papua New Guinea',
    gjhdqywjc: 'PAPUANEWGUINEA',
    gjhdqszm_dm: 'PNG',
    gjhdqlzm_dm: 'PG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '826',
    gjhdqmc: '大不列颠及北爱尔兰联合王国',
    gjhdqjc: '英国',
    gjhdqywmc: 'United Kingdom of Great Britainand Northern Ireland',
    gjhdqywjc: 'UNITEDKINGDOM',
    gjhdqszm_dm: 'GBR',
    gjhdqlzm_dm: 'GB',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '716',
    gjhdqmc: '津巴布韦共和国',
    gjhdqjc: '津巴布韦',
    gjhdqywmc: 'Republic of Zimbabwe',
    gjhdqywjc: 'ZIMBABWE',
    gjhdqszm_dm: 'ZWE',
    gjhdqlzm_dm: 'ZW',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '728',
    gjhdqmc: '南苏丹',
    gjhdqjc: '南苏丹',
    gjhdqywmc: 'South Sudan',
    gjhdqywjc: 'SOUTH SUDAN',
    gjhdqszm_dm: 'SSD',
    gjhdqlzm_dm: 'SS',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '222',
    gjhdqmc: '萨尔瓦多共和国',
    gjhdqjc: '萨尔瓦多',
    gjhdqywmc: 'Republic of El Salvador',
    gjhdqywjc: 'ELSALVADOR',
    gjhdqszm_dm: 'SLV',
    gjhdqlzm_dm: 'SV',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '232',
    gjhdqmc: '厄立特里亚国',
    gjhdqjc: '厄立特里亚',
    gjhdqywmc: 'State of Eritrea',
    gjhdqywjc: 'ERITREA',
    gjhdqszm_dm: 'ERI',
    gjhdqlzm_dm: 'ER',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '404',
    gjhdqmc: '肯尼亚共和国',
    gjhdqjc: '肯尼亚',
    gjhdqywmc: 'Republic of Kenya',
    gjhdqywjc: 'KENYA',
    gjhdqszm_dm: 'KEN',
    gjhdqlzm_dm: 'KE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '422',
    gjhdqmc: '黎巴嫩共和国',
    gjhdqjc: '黎巴嫩',
    gjhdqywmc: 'Lebanese Republic',
    gjhdqywjc: 'LEBANON',
    gjhdqszm_dm: 'LBN',
    gjhdqlzm_dm: 'LB',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '528',
    gjhdqmc: '荷兰王国',
    gjhdqjc: '荷兰',
    gjhdqywmc: 'Kingdom of the Netherlands',
    gjhdqywjc: 'NETHERLANDS',
    gjhdqszm_dm: 'NLD',
    gjhdqlzm_dm: 'NL',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '558',
    gjhdqmc: '尼加拉瓜共和国',
    gjhdqjc: '尼加拉瓜',
    gjhdqywmc: 'Republic of Nicaragua',
    gjhdqywjc: 'NICARAGUA',
    gjhdqszm_dm: 'NIC',
    gjhdqlzm_dm: 'NI',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '612',
    gjhdqmc: '皮特凯恩',
    gjhdqjc: '皮特凯恩',
    gjhdqywmc: 'Pitcairn',
    gjhdqywjc: 'PITCAIRN',
    gjhdqszm_dm: 'PCN',
    gjhdqlzm_dm: 'PN',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '882',
    gjhdqmc: '萨摩亚独立国',
    gjhdqjc: '萨摩亚',
    gjhdqywmc: 'Independent State of Samoa',
    gjhdqywjc: 'SAMOA',
    gjhdqszm_dm: 'WSM',
    gjhdqlzm_dm: 'WS',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '804',
    gjhdqmc: '乌克兰',
    gjhdqjc: '乌克兰',
    gjhdqywmc: 'Ukraine',
    gjhdqywjc: 'UKRAINE',
    gjhdqszm_dm: 'UKR',
    gjhdqlzm_dm: 'UA',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '051',
    gjhdqmc: '亚美尼亚共和国',
    gjhdqjc: '亚美尼亚',
    gjhdqywmc: 'Republic of Armenia',
    gjhdqywjc: 'ARMENIA',
    gjhdqszm_dm: 'ARM',
    gjhdqlzm_dm: 'AM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '136',
    gjhdqmc: '开曼群岛',
    gjhdqjc: '开曼群岛',
    gjhdqywmc: 'Cayman Islands',
    gjhdqywjc: 'CAYMANISLANDS',
    gjhdqszm_dm: 'CYM',
    gjhdqlzm_dm: 'KY',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '180',
    gjhdqmc: '刚果民主共和国',
    gjhdqjc: '刚果（金）',
    gjhdqywmc: 'Democratic Republic of Congo',
    gjhdqywjc: 'CONGO，THEDEMOCRATICREPUBLICOFTHE',
    gjhdqszm_dm: 'COD',
    gjhdqlzm_dm: 'CD',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '352',
    gjhdqmc: '冰岛共和国',
    gjhdqjc: '冰岛',
    gjhdqywmc: 'Republic of Iceland',
    gjhdqywjc: 'ICELAND',
    gjhdqszm_dm: 'ISL',
    gjhdqlzm_dm: 'IS',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '368',
    gjhdqmc: '伊拉克共和国',
    gjhdqjc: '伊拉克',
    gjhdqywmc: 'Republic of Iraq',
    gjhdqywjc: 'IRAQ',
    gjhdqszm_dm: 'IRQ',
    gjhdqlzm_dm: 'IQ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '458',
    gjhdqmc: '马来西亚',
    gjhdqjc: '马来西亚',
    gjhdqywmc: 'Malaysia',
    gjhdqywjc: 'MALAYSIA',
    gjhdqszm_dm: 'MYS',
    gjhdqlzm_dm: 'MY',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '584',
    gjhdqmc: '马绍尔群岛共和国',
    gjhdqjc: '马绍尔群岛',
    gjhdqywmc: 'Republic of the Marshall Islands',
    gjhdqywjc: 'MARSHALLISLANDS',
    gjhdqszm_dm: 'MHL',
    gjhdqlzm_dm: 'MH',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '508',
    gjhdqmc: '莫桑比克共和国',
    gjhdqjc: '莫桑比克',
    gjhdqywmc: 'Republic of Mozambique',
    gjhdqywjc: 'MOZAMBIQUE',
    gjhdqszm_dm: 'MOZ',
    gjhdqlzm_dm: 'MZ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '654',
    gjhdqmc: '圣赫勒拿',
    gjhdqjc: '圣赫勒拿',
    gjhdqywmc: 'Saint Helena',
    gjhdqywjc: 'SAINTHELENA',
    gjhdqszm_dm: 'SHN',
    gjhdqlzm_dm: 'SH',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '694',
    gjhdqmc: '塞拉利昂共和国',
    gjhdqjc: '塞拉利昂',
    gjhdqywmc: 'Republic of Sierra Leone',
    gjhdqywjc: 'SIERRALEONE',
    gjhdqszm_dm: 'SLE',
    gjhdqlzm_dm: 'SL',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '174',
    gjhdqmc: '科摩罗伊斯兰联邦共和国',
    gjhdqjc: '科摩罗',
    gjhdqywmc: 'Islamic Federal Republic of the Comoros',
    gjhdqywjc: 'COMOROS',
    gjhdqszm_dm: 'COM',
    gjhdqlzm_dm: 'KM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '184',
    gjhdqmc: '库克群岛',
    gjhdqjc: '库克群岛',
    gjhdqywmc: 'Cook Islands',
    gjhdqywjc: 'COOKISLANDS',
    gjhdqszm_dm: 'COK',
    gjhdqlzm_dm: 'CK',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '226',
    gjhdqmc: '赤道几内亚共和国',
    gjhdqjc: '赤道几内亚',
    gjhdqywmc: 'Republic of Equatorial Guinea',
    gjhdqywjc: 'EQUATORIALGUINEA',
    gjhdqszm_dm: 'GNQ',
    gjhdqlzm_dm: 'GQ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '304',
    gjhdqmc: '格陵兰',
    gjhdqjc: '格陵兰',
    gjhdqywmc: 'Greenland',
    gjhdqywjc: 'GREENLAND',
    gjhdqszm_dm: 'GRL',
    gjhdqlzm_dm: 'GL',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '104',
    gjhdqmc: '缅甸联邦',
    gjhdqjc: '缅甸',
    gjhdqywmc: 'Union of Myanmar',
    gjhdqywjc: 'MYANMAR',
    gjhdqszm_dm: 'MMR',
    gjhdqlzm_dm: 'MM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '638',
    gjhdqmc: '留尼汪',
    gjhdqjc: '留尼汪',
    gjhdqywmc: 'Reunion',
    gjhdqywjc: 'REUNION',
    gjhdqszm_dm: 'REU',
    gjhdqlzm_dm: 'RE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '659',
    gjhdqmc: '圣基茨和尼维斯联邦',
    gjhdqjc: '圣基茨和尼维斯',
    gjhdqywmc: 'Federation of Saint Kittsand Nevis',
    gjhdqywjc: 'SAINTKITTSANDNEVIS',
    gjhdqszm_dm: 'KNA',
    gjhdqlzm_dm: 'KN',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '702',
    gjhdqmc: '新加坡共和国',
    gjhdqjc: '新加坡',
    gjhdqywmc: 'Republic of Singapore',
    gjhdqywjc: 'SINGAPORE',
    gjhdqszm_dm: 'SGP',
    gjhdqlzm_dm: 'SG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '768',
    gjhdqmc: '多哥共和国',
    gjhdqjc: '多哥',
    gjhdqywmc: 'Republic of Togo',
    gjhdqywjc: 'TOGO',
    gjhdqszm_dm: 'TGO',
    gjhdqlzm_dm: 'TG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '548',
    gjhdqmc: '瓦努阿图共和国',
    gjhdqjc: '瓦努阿图',
    gjhdqywmc: 'Republic of Vanuatu',
    gjhdqywjc: 'VANUATU',
    gjhdqszm_dm: 'VUT',
    gjhdqlzm_dm: 'VU',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '040',
    gjhdqmc: '奥地利共和国',
    gjhdqjc: '奥地利',
    gjhdqywmc: 'Republic of Austria',
    gjhdqywjc: 'AUSTRIA',
    gjhdqszm_dm: 'AUT',
    gjhdqlzm_dm: 'AT',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '056',
    gjhdqmc: '比利时王国',
    gjhdqjc: '比利时',
    gjhdqywmc: 'Kingdom of Belgium',
    gjhdqywjc: 'BELGIUM',
    gjhdqszm_dm: 'BEL',
    gjhdqlzm_dm: 'BE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '132',
    gjhdqmc: '佛得角共和国',
    gjhdqjc: '佛得角',
    gjhdqywmc: 'Republic of CapeVerde',
    gjhdqywjc: 'CAPEVERDE',
    gjhdqszm_dm: 'CPV',
    gjhdqlzm_dm: 'CV',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '208',
    gjhdqmc: '丹麦王国',
    gjhdqjc: '丹麦',
    gjhdqywmc: 'Kingdom of Denmark',
    gjhdqywjc: 'DENMARK',
    gjhdqszm_dm: 'DNK',
    gjhdqlzm_dm: 'DK',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '276',
    gjhdqmc: '德意志联邦共和国',
    gjhdqjc: '德国',
    gjhdqywmc: 'Federal Republic of Germany',
    gjhdqywjc: 'GERMANY',
    gjhdqszm_dm: 'DEU',
    gjhdqlzm_dm: 'DE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '308',
    gjhdqmc: '格林纳达',
    gjhdqjc: '格林纳达',
    gjhdqywmc: 'Grenada',
    gjhdqywjc: 'GRENADA',
    gjhdqszm_dm: 'GRD',
    gjhdqlzm_dm: 'GD',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '440',
    gjhdqmc: '立陶宛共和国',
    gjhdqjc: '立陶宛',
    gjhdqywmc: 'Republic of Lithuania',
    gjhdqywjc: 'LITHUANIA',
    gjhdqszm_dm: 'LTU',
    gjhdqlzm_dm: 'LT',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '474',
    gjhdqmc: '马提尼克',
    gjhdqjc: '马提尼克',
    gjhdqywmc: 'Martinique',
    gjhdqywjc: 'MARTINIQUE',
    gjhdqszm_dm: 'MTQ',
    gjhdqlzm_dm: 'MQ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '478',
    gjhdqmc: '毛里塔尼亚伊斯兰共和国',
    gjhdqjc: '毛里塔尼亚',
    gjhdqywmc: 'Islamic Republic of Mauritania',
    gjhdqywjc: 'MAURITANIA',
    gjhdqszm_dm: 'MRT',
    gjhdqlzm_dm: 'MR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '484',
    gjhdqmc: '墨西哥合众国',
    gjhdqjc: '墨西哥',
    gjhdqywmc: 'United States of Mexico',
    gjhdqywjc: 'MEXICO',
    gjhdqszm_dm: 'MEX',
    gjhdqlzm_dm: 'MX',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '620',
    gjhdqmc: '葡萄牙共和国',
    gjhdqjc: '葡萄牙',
    gjhdqywmc: 'Portuguese Republic',
    gjhdqywjc: 'PORTUGAL',
    gjhdqszm_dm: 'PRT',
    gjhdqlzm_dm: 'PT',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '031',
    gjhdqmc: '阿塞拜疆共和国',
    gjhdqjc: '阿塞拜疆',
    gjhdqywmc: 'Republic of Azerbaijan',
    gjhdqywjc: 'AZERBAIJAN',
    gjhdqszm_dm: 'AZE',
    gjhdqlzm_dm: 'AZ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '116',
    gjhdqmc: '柬埔寨王国',
    gjhdqjc: '柬埔寨',
    gjhdqywmc: 'Kingdom of Cambodia',
    gjhdqywjc: 'CAMBODIA',
    gjhdqszm_dm: 'KHM',
    gjhdqlzm_dm: 'KH',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '231',
    gjhdqmc: '埃塞俄比亚联邦民主共和国',
    gjhdqjc: '埃塞俄比亚',
    gjhdqywmc: 'Federal Democratic Republic of Ethiopia',
    gjhdqywjc: 'ETHIOPIA',
    gjhdqszm_dm: 'ETH',
    gjhdqlzm_dm: 'ET',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '324',
    gjhdqmc: '几内亚共和国',
    gjhdqjc: '几内亚',
    gjhdqywmc: 'Republic of Guinea',
    gjhdqywjc: 'GUINEA',
    gjhdqszm_dm: 'GIN',
    gjhdqlzm_dm: 'GN',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '334',
    gjhdqmc: '赫德岛和麦克唐纳岛',
    gjhdqjc: '赫德岛和麦克唐纳岛',
    gjhdqywmc: 'Heard Islandand Mcdonald Islands',
    gjhdqywjc: 'HEARDISLANDANDMCDONALDISLANDS',
    gjhdqszm_dm: 'HMD',
    gjhdqlzm_dm: 'HM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '296',
    gjhdqmc: '基里巴斯共和国',
    gjhdqjc: '基里巴斯',
    gjhdqywmc: 'Republic of Kiribati',
    gjhdqywjc: 'KIRIBATI',
    gjhdqszm_dm: 'KIR',
    gjhdqlzm_dm: 'KI',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '426',
    gjhdqmc: '莱索托王国',
    gjhdqjc: '莱索托',
    gjhdqywmc: 'Kingdom of Lesotho',
    gjhdqywjc: 'LESOTHO',
    gjhdqszm_dm: 'LSO',
    gjhdqlzm_dm: 'LS',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '807',
    gjhdqmc: '前南斯拉夫马其顿共和国',
    gjhdqjc: '前南马其顿',
    gjhdqywmc: 'Theformer Yugoslav Republic of Macedonia',
    gjhdqywjc: 'MACEDONIA，THEFORMERYUGOSLAVREPUBLICOF',
    gjhdqszm_dm: 'MKD',
    gjhdqlzm_dm: 'MK',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '462',
    gjhdqmc: '马尔代夫共和国',
    gjhdqjc: '马尔代夫',
    gjhdqywmc: 'Republic of Maldives',
    gjhdqywjc: 'MALDIVES',
    gjhdqszm_dm: 'MDV',
    gjhdqlzm_dm: 'MV',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '760',
    gjhdqmc: '阿拉伯叙利亚共和国',
    gjhdqjc: '叙利亚',
    gjhdqywmc: 'Syrian Arab Republic',
    gjhdqywjc: 'SYRIANARABREPUBLIC',
    gjhdqszm_dm: 'SYR',
    gjhdqlzm_dm: 'SY',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '800',
    gjhdqmc: '乌干达共和国',
    gjhdqjc: '乌干达',
    gjhdqywmc: 'Republic of Uganda',
    gjhdqywjc: 'UGANDA',
    gjhdqszm_dm: 'UGA',
    gjhdqlzm_dm: 'UG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '092',
    gjhdqmc: '英属维尔京群岛',
    gjhdqjc: '英属维尔京群岛',
    gjhdqywmc: 'British Virgin Islands',
    gjhdqywjc: 'VIRGINISLANDS，BRITISH',
    gjhdqszm_dm: 'VGB',
    gjhdqlzm_dm: 'VG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '876',
    gjhdqmc: '瓦利斯和富图纳',
    gjhdqjc: '瓦利斯和富图纳',
    gjhdqywmc: 'Wallisand Futuna',
    gjhdqywjc: 'WALLISANDFUTUNA',
    gjhdqszm_dm: 'WLF',
    gjhdqlzm_dm: 'WF',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '384',
    gjhdqmc: '科特迪瓦共和国',
    gjhdqjc: '科特迪瓦',
    gjhdqywmc: "Republic of Coted'Ivoire",
    gjhdqywjc: "COTED'IVOIRE",
    gjhdqszm_dm: 'CIV',
    gjhdqlzm_dm: 'CI',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '831',
    gjhdqmc: '根西岛',
    gjhdqjc: '根西岛',
    gjhdqywmc: 'GUERNSEY',
    gjhdqywjc: 'GUERNSEY',
    gjhdqszm_dm: 'GGY',
    gjhdqlzm_dm: 'GG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '410',
    gjhdqmc: '大韩民国',
    gjhdqjc: '韩国',
    gjhdqywmc: 'Republic of Korea',
    gjhdqywjc: 'KOREA，REPUBLICOF',
    gjhdqszm_dm: 'KOR',
    gjhdqlzm_dm: 'KR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '175',
    gjhdqmc: '马约特',
    gjhdqjc: '马约特',
    gjhdqywmc: 'Mayotte',
    gjhdqywjc: 'MAYOTTE',
    gjhdqszm_dm: 'MYT',
    gjhdqlzm_dm: 'YT',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '630',
    gjhdqmc: '波多黎各',
    gjhdqjc: '波多黎各',
    gjhdqywmc: 'Puerto Rico',
    gjhdqywjc: 'PUERTORICO',
    gjhdqszm_dm: 'PRI',
    gjhdqlzm_dm: 'PR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '740',
    gjhdqmc: '苏里南共和国',
    gjhdqjc: '苏里南',
    gjhdqywmc: 'Republic of Suriname',
    gjhdqywjc: 'SURINAME',
    gjhdqszm_dm: 'SUR',
    gjhdqlzm_dm: 'SR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '764',
    gjhdqmc: '泰王国',
    gjhdqjc: '泰国',
    gjhdqywmc: 'Kingdom of Thailand',
    gjhdqywjc: 'THAILAND',
    gjhdqszm_dm: 'THA',
    gjhdqlzm_dm: 'TH',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '788',
    gjhdqmc: '突尼斯共和国',
    gjhdqjc: '突尼斯',
    gjhdqywmc: 'Republic of Tunisia',
    gjhdqywjc: 'TUNISIA',
    gjhdqszm_dm: 'TUN',
    gjhdqlzm_dm: 'TN',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '064',
    gjhdqmc: '不丹王国',
    gjhdqjc: '不丹',
    gjhdqywmc: 'Kingdom of Bhutan',
    gjhdqywjc: 'BHUTAN',
    gjhdqszm_dm: 'BTN',
    gjhdqlzm_dm: 'BT',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '262',
    gjhdqmc: '吉布提共和国',
    gjhdqjc: '吉布提',
    gjhdqywmc: 'Republic of Djibouti',
    gjhdqywjc: 'DJIBOUTI',
    gjhdqszm_dm: 'DJI',
    gjhdqlzm_dm: 'DJ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '246',
    gjhdqmc: '芬兰共和国',
    gjhdqjc: '芬兰',
    gjhdqywmc: 'Republic of Finland',
    gjhdqywjc: 'FINLAND',
    gjhdqszm_dm: 'FIN',
    gjhdqlzm_dm: 'FI',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '328',
    gjhdqmc: '圭亚那合作共和国',
    gjhdqjc: '圭亚那',
    gjhdqywmc: 'Cooperative Republic of Guyana',
    gjhdqywjc: 'GUYANA',
    gjhdqszm_dm: 'GUY',
    gjhdqlzm_dm: 'GY',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '400',
    gjhdqmc: '约旦哈希姆王国',
    gjhdqjc: '约旦',
    gjhdqywmc: 'Hashemite Kingdom of Jordan',
    gjhdqywjc: 'JORDAN',
    gjhdqszm_dm: 'JOP',
    gjhdqlzm_dm: 'JO',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '450',
    gjhdqmc: '马达加斯加共和国',
    gjhdqjc: '马达加斯加',
    gjhdqywmc: 'Republic of Madagascar',
    gjhdqywjc: 'MADAGASCAR',
    gjhdqszm_dm: 'MDG',
    gjhdqlzm_dm: 'MG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '470',
    gjhdqmc: '马耳他共和国',
    gjhdqjc: '马耳他',
    gjhdqywmc: 'Republic of Malta',
    gjhdqywjc: 'MALTA',
    gjhdqszm_dm: 'MLT',
    gjhdqlzm_dm: 'MT',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '498',
    gjhdqmc: '摩尔多瓦共和国',
    gjhdqjc: '摩尔多瓦',
    gjhdqywmc: 'Republic of Moldova',
    gjhdqywjc: 'MOLDOVA',
    gjhdqszm_dm: 'MDA',
    gjhdqlzm_dm: 'MD',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '705',
    gjhdqmc: '斯洛文尼亚共和国',
    gjhdqjc: '斯洛文尼亚',
    gjhdqywmc: 'Republic of Slovenia',
    gjhdqywjc: 'SLOVENIA',
    gjhdqszm_dm: 'SVN',
    gjhdqlzm_dm: 'SI',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '239',
    gjhdqmc: '南乔治亚岛和南桑德韦奇岛',
    gjhdqjc: '南乔治亚岛和南桑德韦奇岛',
    gjhdqywmc: 'South Georgia and the South Sandwich Islands',
    gjhdqywjc: 'SOUTHGEORGIAANDTHESOUTHSANDWICHISLANDS',
    gjhdqszm_dm: 'SGS',
    gjhdqlzm_dm: 'GS',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '756',
    gjhdqmc: '瑞士联邦',
    gjhdqjc: '瑞士',
    gjhdqywmc: 'Swiss Confederation',
    gjhdqywjc: 'SWITZERLAND',
    gjhdqszm_dm: 'CHE',
    gjhdqlzm_dm: 'CH',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '192',
    gjhdqmc: '古巴共和国',
    gjhdqjc: '古巴',
    gjhdqywmc: 'Republic of Cuba',
    gjhdqywjc: 'CUBA',
    gjhdqszm_dm: 'CUB',
    gjhdqlzm_dm: 'CU',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '203',
    gjhdqmc: '捷克共和国',
    gjhdqjc: '捷克',
    gjhdqywmc: 'Czech Republic',
    gjhdqywjc: 'CZECHREPUBLIC',
    gjhdqszm_dm: 'CZE',
    gjhdqlzm_dm: 'CZ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '268',
    gjhdqmc: '格鲁吉亚',
    gjhdqjc: '格鲁吉亚',
    gjhdqywmc: 'Georgia',
    gjhdqywjc: 'GEORGIA',
    gjhdqszm_dm: 'GEO',
    gjhdqlzm_dm: 'GE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '288',
    gjhdqmc: '加纳共和国',
    gjhdqjc: '加纳',
    gjhdqywmc: 'Republic of Ghana',
    gjhdqywjc: 'GHANA',
    gjhdqszm_dm: 'GHA',
    gjhdqlzm_dm: 'GH',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '417',
    gjhdqmc: '吉尔吉斯共和国',
    gjhdqjc: '吉尔吉斯斯坦',
    gjhdqywmc: 'Kyrgyz Republic',
    gjhdqywjc: 'KYRGYZSTAN',
    gjhdqszm_dm: 'KGZ',
    gjhdqlzm_dm: 'KG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '418',
    gjhdqmc: '老挝人民民主共和国',
    gjhdqjc: '老挝',
    gjhdqywmc: "Lao People's Democratic Republic",
    gjhdqywjc: 'LAOS',
    gjhdqszm_dm: 'LAO',
    gjhdqlzm_dm: 'LA',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '438',
    gjhdqmc: '列支敦士登公国',
    gjhdqjc: '列支敦士登',
    gjhdqywmc: 'Principality of Liechtenstein',
    gjhdqywjc: 'LIECHTENSTEIN',
    gjhdqszm_dm: 'LIE',
    gjhdqlzm_dm: 'LI',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '570',
    gjhdqmc: '纽埃',
    gjhdqjc: '纽埃',
    gjhdqywmc: 'Niue',
    gjhdqywjc: 'NIUE',
    gjhdqszm_dm: 'NIU',
    gjhdqlzm_dm: 'NU',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '643',
    gjhdqmc: '俄罗斯联邦',
    gjhdqjc: '俄罗斯联邦',
    gjhdqywmc: 'Russian Federation',
    gjhdqywjc: 'RUSSIANFEDERATION',
    gjhdqszm_dm: 'RUS',
    gjhdqlzm_dm: 'RU',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '581',
    gjhdqmc: '美国本土外小岛屿',
    gjhdqjc: '美国本土外小岛屿',
    gjhdqywmc: 'United States Minor Outlying Islands',
    gjhdqywjc: 'UNITEDSTATESMINOROUTLYINGISLANDS',
    gjhdqszm_dm: 'UMI',
    gjhdqlzm_dm: 'UM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '732',
    gjhdqmc: '西撒哈拉',
    gjhdqjc: '西撒哈拉',
    gjhdqywmc: 'Western Sahara',
    gjhdqywjc: 'WESTERNSAHARA',
    gjhdqszm_dm: 'ESH',
    gjhdqlzm_dm: 'EH',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '016',
    gjhdqmc: '美属萨摩亚',
    gjhdqjc: '美属萨摩亚',
    gjhdqywmc: 'American Samoa',
    gjhdqywjc: 'AMERICANSAMOA',
    gjhdqszm_dm: 'ASM',
    gjhdqlzm_dm: 'AS',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '072',
    gjhdqmc: '博茨瓦纳共和国',
    gjhdqjc: '博茨瓦纳',
    gjhdqywmc: 'Republic of Botswana',
    gjhdqywjc: 'BOTSWANA',
    gjhdqszm_dm: 'BWA',
    gjhdqlzm_dm: 'BW',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '076',
    gjhdqmc: '巴西联邦共和国',
    gjhdqjc: '巴西',
    gjhdqywmc: 'Federative Republic of Brazil',
    gjhdqywjc: 'BRAZIL',
    gjhdqszm_dm: 'BRA',
    gjhdqlzm_dm: 'BR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '446',
    gjhdqmc: '中国澳门特别行政区',
    gjhdqjc: '中国澳门',
    gjhdqywmc: 'Macau Special Administrative Region of China',
    gjhdqywjc: 'MACAU',
    gjhdqszm_dm: 'MAC',
    gjhdqlzm_dm: 'MO',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '162',
    gjhdqmc: '圣诞岛',
    gjhdqjc: '圣诞岛',
    gjhdqywmc: 'Christmas Island',
    gjhdqywjc: 'CHRISTMASISLAND',
    gjhdqszm_dm: 'CXR',
    gjhdqlzm_dm: 'CX',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '170',
    gjhdqmc: '哥伦比亚共和国',
    gjhdqjc: '哥伦比亚',
    gjhdqywmc: 'Republic of Colombia',
    gjhdqywjc: 'COLOMBIA',
    gjhdqszm_dm: 'COL',
    gjhdqlzm_dm: 'CO',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '260',
    gjhdqmc: '法属南部领地',
    gjhdqjc: '法属南部领地',
    gjhdqywmc: 'French Southern Territories',
    gjhdqywjc: 'FRENCHSOUTHERNTERRITORIES',
    gjhdqszm_dm: 'ATF',
    gjhdqlzm_dm: 'TF',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '372',
    gjhdqmc: '爱尔兰',
    gjhdqjc: '爱尔兰',
    gjhdqywmc: 'Ireland',
    gjhdqywjc: 'IRELAND',
    gjhdqszm_dm: 'IRL',
    gjhdqlzm_dm: 'IE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '480',
    gjhdqmc: '毛里求斯共和国',
    gjhdqjc: '毛里求斯',
    gjhdqywmc: 'Republic of Mauritius',
    gjhdqywjc: 'MAURITIUS',
    gjhdqszm_dm: 'MUS',
    gjhdqlzm_dm: 'MU',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '540',
    gjhdqmc: '新喀里多尼亚',
    gjhdqjc: '新喀里多尼亚',
    gjhdqywmc: 'New Caledonia',
    gjhdqywjc: 'NEWCALEDONIA',
    gjhdqszm_dm: 'NCL',
    gjhdqlzm_dm: 'NC',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '642',
    gjhdqmc: '罗马尼亚',
    gjhdqjc: '罗马尼亚',
    gjhdqywmc: 'Romania',
    gjhdqywjc: 'ROMANIA',
    gjhdqszm_dm: 'ROM',
    gjhdqlzm_dm: 'RO',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '710',
    gjhdqmc: '南非共和国',
    gjhdqjc: '南非',
    gjhdqywmc: 'Republic of SouthAfrica',
    gjhdqywjc: 'SOUTHAFRICA',
    gjhdqszm_dm: 'ZAF',
    gjhdqlzm_dm: 'ZA',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '784',
    gjhdqmc: '阿拉伯联合酋长国',
    gjhdqjc: '阿联酋',
    gjhdqywmc: 'United Arab Emirates',
    gjhdqywjc: 'UNITEDARABEMIRATES',
    gjhdqszm_dm: 'ARE',
    gjhdqlzm_dm: 'AE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '862',
    gjhdqmc: '委内瑞拉共和国',
    gjhdqjc: '委内瑞拉',
    gjhdqywmc: 'Republic of Venezuela',
    gjhdqywjc: 'VENEZUELA',
    gjhdqszm_dm: 'VEN',
    gjhdqlzm_dm: 'VE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '086',
    gjhdqmc: '英属印度洋领地',
    gjhdqjc: '英属印度洋领地',
    gjhdqywmc: 'British Indian Ocean Territory',
    gjhdqywjc: 'BRITISHINDIANOCEANTERRITORY',
    gjhdqszm_dm: 'IOT',
    gjhdqlzm_dm: 'IO',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '178',
    gjhdqmc: '刚果共和国',
    gjhdqjc: '刚果（布）',
    gjhdqywmc: 'Republic of Congo',
    gjhdqywjc: 'CONGO',
    gjhdqszm_dm: 'COG',
    gjhdqlzm_dm: 'CG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '364',
    gjhdqmc: '伊朗伊斯兰共和国',
    gjhdqjc: '伊朗',
    gjhdqywmc: 'Islamic Republic of Iran',
    gjhdqywjc: 'IRAN',
    gjhdqszm_dm: 'IRN',
    gjhdqlzm_dm: 'IR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '454',
    gjhdqmc: '马拉维共和国',
    gjhdqjc: '马拉维',
    gjhdqywmc: 'Republic of Malawi',
    gjhdqywjc: 'MALAWI',
    gjhdqszm_dm: 'MWI',
    gjhdqlzm_dm: 'MW',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '524',
    gjhdqmc: '尼泊尔王国',
    gjhdqjc: '尼泊尔',
    gjhdqywmc: 'Kingdom of Nepal',
    gjhdqywjc: 'NEPAL',
    gjhdqszm_dm: 'NPL',
    gjhdqlzm_dm: 'NP',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '634',
    gjhdqmc: '卡塔尔国',
    gjhdqjc: '卡塔尔',
    gjhdqywmc: 'State of Qatar',
    gjhdqywjc: 'QATAR',
    gjhdqszm_dm: 'QAT',
    gjhdqlzm_dm: 'QA',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '834',
    gjhdqmc: '坦桑尼亚联合共和国',
    gjhdqjc: '坦桑尼亚',
    gjhdqywmc: 'United Republic of Tanzania',
    gjhdqywjc: 'TANZANIA',
    gjhdqszm_dm: 'TZA',
    gjhdqlzm_dm: 'TZ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '776',
    gjhdqmc: '汤加王国',
    gjhdqjc: '汤加',
    gjhdqywmc: 'Kingdom of Tonga',
    gjhdqywjc: 'TONGA',
    gjhdqszm_dm: 'TON',
    gjhdqlzm_dm: 'TO',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '204',
    gjhdqmc: '贝宁共和国',
    gjhdqjc: '贝宁',
    gjhdqywmc: 'Republic of Benin',
    gjhdqywjc: 'BENIN',
    gjhdqszm_dm: 'BEN',
    gjhdqlzm_dm: 'BJ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '100',
    gjhdqmc: '保加利亚共和国',
    gjhdqjc: '保加利亚',
    gjhdqywmc: 'Republic of Bulgaria',
    gjhdqywjc: 'BULGARIA',
    gjhdqszm_dm: 'BGR',
    gjhdqlzm_dm: 'BG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '140',
    gjhdqmc: '中非共和国',
    gjhdqjc: '中非',
    gjhdqywmc: 'Central African Republic',
    gjhdqywjc: 'CENTRALAFRICANREPUBLIC',
    gjhdqszm_dm: 'CAF',
    gjhdqlzm_dm: 'CF',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '214',
    gjhdqmc: '多米尼加共和国',
    gjhdqjc: '多米尼加',
    gjhdqywmc: 'Dominican Republic',
    gjhdqywjc: 'DOMINICANREPUBLIC',
    gjhdqszm_dm: 'DOM',
    gjhdqlzm_dm: 'DO',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '340',
    gjhdqmc: '洪都拉斯共和国',
    gjhdqjc: '洪都拉斯',
    gjhdqywmc: 'Republic of Honduras',
    gjhdqywjc: 'HONDURAS',
    gjhdqszm_dm: 'HND',
    gjhdqlzm_dm: 'HN',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '356',
    gjhdqmc: '印度共和国',
    gjhdqjc: '印度',
    gjhdqywmc: 'Republic of India',
    gjhdqywjc: 'INDIA',
    gjhdqszm_dm: 'IND',
    gjhdqlzm_dm: 'IN',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '360',
    gjhdqmc: '印度尼西亚共和国',
    gjhdqjc: '印度尼西亚',
    gjhdqywmc: 'Republic of Indonesia',
    gjhdqywjc: 'INDONESIA',
    gjhdqszm_dm: 'IDN',
    gjhdqlzm_dm: 'ID',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '380',
    gjhdqmc: '意大利共和国',
    gjhdqjc: '意大利',
    gjhdqywmc: 'Italian Republic',
    gjhdqywjc: 'ITALY',
    gjhdqszm_dm: 'ITA',
    gjhdqlzm_dm: 'IT',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '583',
    gjhdqmc: '密克罗尼西亚联邦',
    gjhdqjc: '密克罗尼西亚联邦',
    gjhdqywmc: 'Federated States of Micronesia',
    gjhdqywjc: 'MICRONESIA，FEDERATEDSTATESOF',
    gjhdqszm_dm: 'FSM',
    gjhdqlzm_dm: 'FM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '562',
    gjhdqmc: '尼日尔共和国',
    gjhdqjc: '尼日尔',
    gjhdqywmc: 'Republic of Niger',
    gjhdqywjc: 'NIGER',
    gjhdqszm_dm: 'NER',
    gjhdqlzm_dm: 'NE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '703',
    gjhdqmc: '斯洛伐克共和国',
    gjhdqjc: '斯洛伐克',
    gjhdqywmc: 'Slovak Republic',
    gjhdqywjc: 'SLOVAKIA',
    gjhdqszm_dm: 'SVK',
    gjhdqlzm_dm: 'SK',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '688',
    gjhdqmc: '塞尔维亚',
    gjhdqjc: '塞尔维亚',
    gjhdqywmc: 'Serbia',
    gjhdqywjc: 'Serbia',
    gjhdqszm_dm: 'SRB',
    gjhdqlzm_dm: 'RS',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '112',
    gjhdqmc: '白俄罗斯共和国',
    gjhdqjc: '白俄罗斯',
    gjhdqywmc: 'Republic of Belarus',
    gjhdqywjc: 'BELARUS',
    gjhdqszm_dm: 'BLR',
    gjhdqlzm_dm: 'BY',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '096',
    gjhdqmc: '文莱达鲁萨兰国',
    gjhdqjc: '文莱',
    gjhdqywmc: 'Brunei Darussalam',
    gjhdqywjc: 'BRUNEI',
    gjhdqszm_dm: 'BRN',
    gjhdqlzm_dm: 'BN',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '238',
    gjhdqmc: '福克兰群岛（马尔维纳斯）',
    gjhdqjc: '福克兰群岛（马尔维纳斯）',
    gjhdqywmc: 'Falkland Islands（Malvinas）',
    gjhdqywjc: 'FALKLANDISLANDS（MALVINAS）',
    gjhdqszm_dm: 'FLK',
    gjhdqlzm_dm: 'FK',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '242',
    gjhdqmc: '斐济群岛共和国',
    gjhdqjc: '斐济',
    gjhdqywmc: 'Republic of the Fiji Islands',
    gjhdqywjc: 'FIJI',
    gjhdqszm_dm: 'FJI',
    gjhdqlzm_dm: 'FJ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '408',
    gjhdqmc: '朝鲜民主主义人民共和国',
    gjhdqjc: '朝鲜',
    gjhdqywmc: "Democratic People's Republic of Korea",
    gjhdqywjc: "KOREA，DEMOCRATICPEOPLE'SREPUBLICOF",
    gjhdqszm_dm: 'PRK',
    gjhdqlzm_dm: 'KP',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '414',
    gjhdqmc: '科威特国',
    gjhdqjc: '科威特',
    gjhdqywmc: 'State of Kuwait',
    gjhdqywjc: 'KUWAIT',
    gjhdqszm_dm: 'KWT',
    gjhdqlzm_dm: 'KW',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '591',
    gjhdqmc: '巴拿马共和国',
    gjhdqjc: '巴拿马',
    gjhdqywmc: 'Republic of Panama',
    gjhdqywjc: 'PANAMA',
    gjhdqszm_dm: 'PAN',
    gjhdqlzm_dm: 'PA',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '074',
    gjhdqmc: '布维岛',
    gjhdqjc: '布维岛',
    gjhdqywmc: 'Bouvet Island',
    gjhdqywjc: 'BOUVETISLAND',
    gjhdqszm_dm: 'BVT',
    gjhdqlzm_dm: 'BV',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '108',
    gjhdqmc: '布隆迪共和国',
    gjhdqjc: '布隆迪',
    gjhdqywmc: 'Republic of Burundi',
    gjhdqywjc: 'BURUNDI',
    gjhdqszm_dm: 'BDI',
    gjhdqlzm_dm: 'BI',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '158',
    gjhdqmc: '中国台湾',
    gjhdqjc: '中国台湾',
    gjhdqywmc: 'Taiwan，Province of China',
    gjhdqywjc: 'TAIWAN,PROVINCE OF CHINA',
    gjhdqszm_dm: 'TWN',
    gjhdqlzm_dm: 'TW',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '388',
    gjhdqmc: '牙买加',
    gjhdqjc: '牙买加',
    gjhdqywmc: 'Jamaica',
    gjhdqywjc: 'JAMAICA',
    gjhdqszm_dm: 'JAM',
    gjhdqlzm_dm: 'JM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '428',
    gjhdqmc: '拉脱维亚共和国',
    gjhdqjc: '拉脱维亚',
    gjhdqywmc: 'Republic of Latvia',
    gjhdqywjc: 'LATVIA',
    gjhdqszm_dm: 'LVA',
    gjhdqlzm_dm: 'LV',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '496',
    gjhdqmc: '蒙古国',
    gjhdqjc: '蒙古',
    gjhdqywmc: 'Mongolia',
    gjhdqywjc: 'MONGOLIA',
    gjhdqszm_dm: 'MNG',
    gjhdqlzm_dm: 'MN',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '090',
    gjhdqmc: '所罗门群岛',
    gjhdqjc: '所罗门群岛',
    gjhdqywmc: 'Solomon Islands',
    gjhdqywjc: 'SOLOMONISLANDS',
    gjhdqszm_dm: 'SLB',
    gjhdqlzm_dm: 'SB',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '724',
    gjhdqmc: '西班牙王国',
    gjhdqjc: '西班牙',
    gjhdqywmc: 'Kingdom of Spain',
    gjhdqywjc: 'SPAIN',
    gjhdqszm_dm: 'ESP',
    gjhdqlzm_dm: 'ES',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '744',
    gjhdqmc: '斯瓦尔巴岛和扬马延岛',
    gjhdqjc: '斯瓦尔巴岛和扬马延岛',
    gjhdqywmc: 'Svalbardand Jan Mayen',
    gjhdqywjc: 'SVALBARDANDJANMAYEN',
    gjhdqszm_dm: 'SJM',
    gjhdqlzm_dm: 'SJ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '748',
    gjhdqmc: '斯威士兰王国',
    gjhdqjc: '斯威士兰',
    gjhdqywmc: 'Kingdom of Swaziland',
    gjhdqywjc: 'SWAZILAND',
    gjhdqszm_dm: 'SWZ',
    gjhdqlzm_dm: 'SZ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '752',
    gjhdqmc: '瑞典王国',
    gjhdqjc: '瑞典',
    gjhdqywmc: 'Kingdom of Sweden',
    gjhdqywjc: 'SWEDEN',
    gjhdqszm_dm: 'SWE',
    gjhdqlzm_dm: 'SE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '860',
    gjhdqmc: '乌兹别克斯坦共和国',
    gjhdqjc: '乌兹别克斯坦',
    gjhdqywmc: 'Republic of Uzbekistan',
    gjhdqywjc: 'UZBEKISTAN',
    gjhdqszm_dm: 'UZB',
    gjhdqlzm_dm: 'UZ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '704',
    gjhdqmc: '越南社会主义共和国',
    gjhdqjc: '越南',
    gjhdqywmc: 'Socialist Republic of Viet Nam',
    gjhdqywjc: 'VIETNAM',
    gjhdqszm_dm: 'VNM',
    gjhdqlzm_dm: 'VN',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '024',
    gjhdqmc: '安哥拉共和国',
    gjhdqjc: '安哥拉',
    gjhdqywmc: 'Republic of Angola',
    gjhdqywjc: 'ANGOLA',
    gjhdqszm_dm: 'AGO',
    gjhdqlzm_dm: 'AO',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '854',
    gjhdqmc: '布基纳法索',
    gjhdqjc: '布基纳法索',
    gjhdqywmc: 'Burkina Faso',
    gjhdqywjc: 'BURKINAFASO',
    gjhdqszm_dm: 'BFA',
    gjhdqlzm_dm: 'BF',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '196',
    gjhdqmc: '塞浦路斯共和国',
    gjhdqjc: '塞浦路斯',
    gjhdqywmc: 'Republic of Cyprus',
    gjhdqywjc: 'CYPRUS',
    gjhdqszm_dm: 'CYP',
    gjhdqlzm_dm: 'CY',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '254',
    gjhdqmc: '法属圭亚那',
    gjhdqjc: '法属圭亚那',
    gjhdqywmc: 'French Guiana',
    gjhdqywjc: 'FRENCHGUIANA',
    gjhdqszm_dm: 'GUF',
    gjhdqlzm_dm: 'GF',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '316',
    gjhdqmc: '关岛',
    gjhdqjc: '关岛',
    gjhdqywmc: 'Guam',
    gjhdqywjc: 'GUAM',
    gjhdqszm_dm: 'GUM',
    gjhdqlzm_dm: 'GU',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '624',
    gjhdqmc: '几内亚比绍共和国',
    gjhdqjc: '几内亚比绍',
    gjhdqywmc: 'Republic of Guinea-Bissau',
    gjhdqywjc: 'GUINEA-BISSAU',
    gjhdqszm_dm: 'GNB',
    gjhdqlzm_dm: 'GW',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '566',
    gjhdqmc: '尼日利亚联邦共和国',
    gjhdqjc: '尼日利亚',
    gjhdqywmc: 'Federal Republic of Nigeria',
    gjhdqywjc: 'NIGERIA',
    gjhdqszm_dm: 'NGA',
    gjhdqlzm_dm: 'NG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '887',
    gjhdqmc: '也门共和国',
    gjhdqjc: '也门',
    gjhdqywmc: 'Republic of Yemen',
    gjhdqywjc: 'YEMEN',
    gjhdqszm_dm: 'YEM',
    gjhdqlzm_dm: 'YE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '028',
    gjhdqmc: '安提瓜和巴布达',
    gjhdqjc: '安提瓜和巴布达',
    gjhdqywmc: 'Antiguaand Barbuda',
    gjhdqywjc: 'ANTIGUAANDBARBUDA',
    gjhdqszm_dm: 'ATG',
    gjhdqlzm_dm: 'AG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '060',
    gjhdqmc: '百慕大',
    gjhdqjc: '百慕大',
    gjhdqywmc: 'Bermuda',
    gjhdqywjc: 'BERMUDA',
    gjhdqszm_dm: 'BMU',
    gjhdqlzm_dm: 'BM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '818',
    gjhdqmc: '阿拉伯埃及共和国',
    gjhdqjc: '埃及',
    gjhdqywmc: 'Arab Republic of Egypt',
    gjhdqywjc: 'EGYPT',
    gjhdqszm_dm: 'EGY',
    gjhdqlzm_dm: 'EG',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '250',
    gjhdqmc: '法兰西共和国',
    gjhdqjc: '法国',
    gjhdqywmc: 'French Republic',
    gjhdqywjc: 'FRANCE',
    gjhdqszm_dm: 'FRA',
    gjhdqlzm_dm: 'FR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '320',
    gjhdqmc: '危地马拉共和国',
    gjhdqjc: '危地马',
    gjhdqywmc: 'Republic of Guatemala',
    gjhdqywjc: 'GUATEMALA',
    gjhdqszm_dm: 'GTM',
    gjhdqlzm_dm: 'GT',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '520',
    gjhdqmc: '瑙鲁共和国',
    gjhdqjc: '瑙鲁',
    gjhdqywmc: 'Republic of Nauru',
    gjhdqywjc: 'NAURU',
    gjhdqszm_dm: 'NRU',
    gjhdqlzm_dm: 'NR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '604',
    gjhdqmc: '秘鲁共和国',
    gjhdqjc: '秘鲁',
    gjhdqywmc: 'Republic of Peru',
    gjhdqywjc: 'PERU',
    gjhdqszm_dm: 'PER',
    gjhdqlzm_dm: 'PE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '616',
    gjhdqmc: '波兰共和国',
    gjhdqjc: '波兰',
    gjhdqywmc: 'Republic of Poland',
    gjhdqywjc: 'POLAND',
    gjhdqszm_dm: 'POL',
    gjhdqlzm_dm: 'PL',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '666',
    gjhdqmc: '圣皮埃尔和密克隆',
    gjhdqjc: '圣皮埃尔和密克隆',
    gjhdqywmc: 'Saint Pierreand Miquelon',
    gjhdqywjc: 'SAINTPIERREANDMIQUELON',
    gjhdqszm_dm: 'SPM',
    gjhdqlzm_dm: 'PM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '690',
    gjhdqmc: '塞舌尔共和国',
    gjhdqjc: '塞舌尔',
    gjhdqywmc: 'Republic of Seychelles',
    gjhdqywjc: 'SEYCHELLES',
    gjhdqszm_dm: 'SYC',
    gjhdqlzm_dm: 'SC',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '762',
    gjhdqmc: '塔吉克斯坦共和国',
    gjhdqjc: '塔吉克斯坦',
    gjhdqywmc: 'Republic of Tajikistan',
    gjhdqywjc: 'TANKISTAN',
    gjhdqszm_dm: 'TJK',
    gjhdqlzm_dm: 'TJ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '792',
    gjhdqmc: '土耳其共和国',
    gjhdqjc: '土耳其',
    gjhdqywmc: 'Republic of Turkey',
    gjhdqywjc: 'TURKEY',
    gjhdqszm_dm: 'TUR',
    gjhdqlzm_dm: 'TR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '233',
    gjhdqmc: '爱沙尼亚共和国',
    gjhdqjc: '爱沙尼亚',
    gjhdqywmc: 'Republic of Estonia',
    gjhdqywjc: 'ESTONIA',
    gjhdqszm_dm: 'EST',
    gjhdqlzm_dm: 'EE',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '258',
    gjhdqmc: '法属波利尼西亚',
    gjhdqjc: '法属波利尼西亚',
    gjhdqywmc: 'French Polynesia',
    gjhdqywjc: 'FRENCHPOLYNESIA',
    gjhdqszm_dm: 'PYF',
    gjhdqlzm_dm: 'PF',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '430',
    gjhdqmc: '利比里亚共和国',
    gjhdqjc: '利比里亚',
    gjhdqywmc: 'Republic of Liberia',
    gjhdqywjc: 'LIBERIA',
    gjhdqszm_dm: 'LBR',
    gjhdqlzm_dm: 'LR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '574',
    gjhdqmc: '诺福克岛',
    gjhdqjc: '诺福克岛',
    gjhdqywmc: 'Norfolk Island',
    gjhdqywjc: 'NORFOLKISLAND',
    gjhdqszm_dm: 'NFK',
    gjhdqlzm_dm: 'NF',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '662',
    gjhdqmc: '圣卢西亚',
    gjhdqjc: '圣卢西亚',
    gjhdqywmc: 'Saint Lucia',
    gjhdqywjc: 'SAINTLUCIA',
    gjhdqszm_dm: 'LCA',
    gjhdqlzm_dm: 'LC',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '144',
    gjhdqmc: '斯里兰卡民主社会主义共和国',
    gjhdqjc: '斯里兰卡',
    gjhdqywmc: 'Democratic Socialist Republic of Sri Lanka',
    gjhdqywjc: 'SRILANKA',
    gjhdqszm_dm: 'LKA',
    gjhdqlzm_dm: 'LK',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '798',
    gjhdqmc: '图瓦卢',
    gjhdqjc: '图瓦卢',
    gjhdqywmc: 'Tuvalu',
    gjhdqywjc: 'TUVALU',
    gjhdqszm_dm: 'TUV',
    gjhdqlzm_dm: 'TV',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '891',
    gjhdqmc: '南斯拉夫联盟共和国',
    gjhdqjc: '南斯拉夫',
    gjhdqywmc: 'Federal Republic of Yugoslavia',
    gjhdqywjc: 'YUGOSLAVIA',
    gjhdqszm_dm: 'YUG',
    gjhdqlzm_dm: 'YU',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '004',
    gjhdqmc: '阿富汗',
    gjhdqjc: '阿富汗',
    gjhdqywmc: 'Afghanistan',
    gjhdqywjc: 'AFGHANISTAN',
    gjhdqszm_dm: 'AFG',
    gjhdqlzm_dm: 'AF',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '036',
    gjhdqmc: '澳大利亚联邦',
    gjhdqjc: '澳大利亚',
    gjhdqywmc: 'Commonwealth of Australia',
    gjhdqywjc: 'AUSTRALIA',
    gjhdqszm_dm: 'AUS',
    gjhdqlzm_dm: 'AU',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '068',
    gjhdqmc: '玻利维亚共和国',
    gjhdqjc: '玻利维亚',
    gjhdqywmc: 'Republic of Bolivia',
    gjhdqywjc: 'BOLIVIA',
    gjhdqszm_dm: 'BOL',
    gjhdqlzm_dm: 'BO',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '152',
    gjhdqmc: '智利共和国',
    gjhdqjc: '智利',
    gjhdqywmc: 'Republic of Chile',
    gjhdqywjc: 'CHILE',
    gjhdqszm_dm: 'CHL',
    gjhdqlzm_dm: 'CL',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '166',
    gjhdqmc: '科科斯（基林）群岛',
    gjhdqjc: '科科斯（基林）群岛',
    gjhdqywmc: 'Cocos（Keeling）Islands',
    gjhdqywjc: 'COCOS（KEELING）ISLANDS',
    gjhdqszm_dm: 'CCK',
    gjhdqlzm_dm: 'CC',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '191',
    gjhdqmc: '克罗地亚共和国',
    gjhdqjc: '克罗地亚',
    gjhdqywmc: 'Republic of Croatia',
    gjhdqywjc: 'CROATIA',
    gjhdqszm_dm: 'HRV',
    gjhdqlzm_dm: 'HR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '292',
    gjhdqmc: '直布罗陀',
    gjhdqjc: '直布罗陀',
    gjhdqywmc: 'Gibraltar',
    gjhdqywjc: 'GIBRALTAR',
    gjhdqszm_dm: 'GIB',
    gjhdqlzm_dm: 'GI',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '434',
    gjhdqmc: '大阿拉伯利比亚人民社会主义民众国',
    gjhdqjc: '利比亚',
    gjhdqywmc: "Great Socialist People's Libyan Arab Jamahiriya",
    gjhdqywjc: 'LIBYA',
    gjhdqszm_dm: 'LBY',
    gjhdqlzm_dm: 'LY',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '442',
    gjhdqmc: '卢森堡大公国',
    gjhdqjc: '卢森堡',
    gjhdqywmc: 'GrandDuchy of Luxembourg',
    gjhdqywjc: 'LUXEMBOURG',
    gjhdqszm_dm: 'LUX',
    gjhdqlzm_dm: 'LU',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '466',
    gjhdqmc: '马里共和国',
    gjhdqjc: '马里',
    gjhdqywmc: 'Republic of Mali',
    gjhdqywjc: 'MALI',
    gjhdqszm_dm: 'MLI',
    gjhdqlzm_dm: 'ML',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '530',
    gjhdqmc: '荷属安的列斯',
    gjhdqjc: '荷属安的列斯',
    gjhdqywmc: 'Netherlands Antilles',
    gjhdqywjc: 'NETHERLANDSANTILLES',
    gjhdqszm_dm: 'ANT',
    gjhdqlzm_dm: 'AN',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '554',
    gjhdqmc: '新西兰',
    gjhdqjc: '新西兰',
    gjhdqywmc: 'New Zealand',
    gjhdqywjc: 'NEWZEALAND',
    gjhdqszm_dm: 'NZL',
    gjhdqlzm_dm: 'NZ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '586',
    gjhdqmc: '巴基斯坦伊斯兰共和国',
    gjhdqjc: '巴基斯坦',
    gjhdqywmc: 'Islamic Republic of Pakistan',
    gjhdqywjc: 'PAKISTAN',
    gjhdqszm_dm: 'PAK',
    gjhdqlzm_dm: 'PK',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '858',
    gjhdqmc: '乌拉圭东岸共和国',
    gjhdqjc: '乌拉圭',
    gjhdqywmc: 'Oriental Republic of Uruguay',
    gjhdqywjc: 'URUGUAY',
    gjhdqszm_dm: 'URY',
    gjhdqlzm_dm: 'UY',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '850',
    gjhdqmc: '美属维尔京群岛',
    gjhdqjc: '美属维尔京群岛',
    gjhdqywmc: 'Virgin Islands of the United States',
    gjhdqywjc: 'VIRGINISLANDS，U.S.',
    gjhdqszm_dm: 'VIR',
    gjhdqlzm_dm: 'VI',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '050',
    gjhdqmc: '孟加拉人民共和国',
    gjhdqjc: '孟加拉国',
    gjhdqywmc: "People's Republic of Bangladesh",
    gjhdqywjc: 'BANGLADESH',
    gjhdqszm_dm: 'BGD',
    gjhdqlzm_dm: 'BD',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '148',
    gjhdqmc: '乍得共和国',
    gjhdqjc: '乍得',
    gjhdqywmc: 'Republic of Chad',
    gjhdqywjc: 'CHAD',
    gjhdqszm_dm: 'TCD',
    gjhdqlzm_dm: 'TD',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '156',
    gjhdqmc: '中华人民共和国',
    gjhdqjc: '中国',
    gjhdqywmc: "People's Republic of China",
    gjhdqywjc: 'CHINA',
    gjhdqszm_dm: 'CHN',
    gjhdqlzm_dm: 'CN',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '376',
    gjhdqmc: '以色列国',
    gjhdqjc: '以色列',
    gjhdqywmc: 'State of Israel',
    gjhdqywjc: 'ISRAEI',
    gjhdqszm_dm: 'ISR',
    gjhdqlzm_dm: 'IL',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '392',
    gjhdqmc: '日本国',
    gjhdqjc: '日本',
    gjhdqywmc: 'Japan',
    gjhdqywjc: 'JAPAN',
    gjhdqszm_dm: 'JPN',
    gjhdqlzm_dm: 'JP',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '512',
    gjhdqmc: '阿曼苏丹国',
    gjhdqjc: '阿曼',
    gjhdqywmc: 'Sultanate of Oman',
    gjhdqywjc: 'OMAN',
    gjhdqszm_dm: 'OMN',
    gjhdqlzm_dm: 'OM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '275',
    gjhdqmc: '巴勒斯坦国',
    gjhdqjc: '巴勒斯坦',
    gjhdqywmc: 'State of Palestine',
    gjhdqywjc: 'PALESTINE',
    gjhdqszm_dm: 'PSE',
    gjhdqlzm_dm: 'PS',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '608',
    gjhdqmc: '菲律宾共和国',
    gjhdqjc: '菲律宾',
    gjhdqywmc: 'Republic of the Philippines',
    gjhdqywjc: 'PHILIPPINES',
    gjhdqszm_dm: 'PHL',
    gjhdqlzm_dm: 'PH',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '686',
    gjhdqmc: '塞内加尔共和国',
    gjhdqjc: '塞内加尔',
    gjhdqywmc: 'Republic of Senegal',
    gjhdqywjc: 'SENEGAL',
    gjhdqszm_dm: 'SEN',
    gjhdqlzm_dm: 'SN',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '706',
    gjhdqmc: '索马里共和国',
    gjhdqjc: '索马里',
    gjhdqywmc: 'Somali Republic',
    gjhdqywjc: 'SOMALIA',
    gjhdqszm_dm: 'SOM',
    gjhdqlzm_dm: 'SO',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '499',
    gjhdqmc: '黑山',
    gjhdqjc: '黑山',
    gjhdqywmc: 'Montenegro',
    gjhdqywjc: 'Montenegro',
    gjhdqszm_dm: 'MNE',
    gjhdqlzm_dm: 'ME',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '020',
    gjhdqmc: '安道尔公国',
    gjhdqjc: '安道尔',
    gjhdqywmc: 'Principality of Andorra',
    gjhdqywjc: 'ANDORRA',
    gjhdqszm_dm: 'AND',
    gjhdqlzm_dm: 'AD',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '660',
    gjhdqmc: '安圭拉',
    gjhdqjc: '安圭拉',
    gjhdqywmc: 'Anguilla',
    gjhdqywjc: 'ANGUILLA',
    gjhdqszm_dm: 'AIA',
    gjhdqlzm_dm: 'AI',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '010',
    gjhdqmc: '南极洲',
    gjhdqjc: '南极洲',
    gjhdqywmc: 'Antarctica',
    gjhdqywjc: 'ANTARCTICA',
    gjhdqszm_dm: 'ATA',
    gjhdqlzm_dm: 'AQ',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '032',
    gjhdqmc: '阿根廷共和国',
    gjhdqjc: '阿根廷',
    gjhdqywmc: 'Argentine Republic',
    gjhdqywjc: 'ARGENTINA',
    gjhdqszm_dm: 'ARG',
    gjhdqlzm_dm: 'AR',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '120',
    gjhdqmc: '喀麦隆共和国',
    gjhdqjc: '喀麦隆',
    gjhdqywmc: 'Republic of Cameroon',
    gjhdqywjc: 'CAMEROON',
    gjhdqszm_dm: 'CMR',
    gjhdqlzm_dm: 'CM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
  {
    gjhdqsz_dm: '212',
    gjhdqmc: '多米尼克国',
    gjhdqjc: '多米尼克',
    gjhdqywmc: 'Commonwealth of Dominica',
    gjhdqywjc: 'DOMINICA',
    gjhdqszm_dm: 'DMA',
    gjhdqlzm_dm: 'DM',
    xybz: 'Y',
    yxbz: 'Y',
    op_ts: '',
    op_type: '',
    kafka_offset: '',
  },
];
